import Link from "next/link";
import { fetchCurrentUser } from "@/lib/server-auth";

const features = [
  {
    title: "Adaptive learning paths",
    description:
      "Unlock curated topics generated by our AI orchestration, complete with Monaco code playgrounds and Judge0 execution.",
  },
  {
    title: "Recruiter-ready profiles",
    description:
      "Maintain a unified profile across learning, assessments, and recruitment dashboards with verified progress gates.",
  },
  {
    title: "Assessment workflows",
    description:
      "Run multi-phase assessments with voice, debugging, coding, and MCQ challenges—fully integrated with session monitoring.",
  },
];

export default async function Home() {
  const session = await fetchCurrentUser();

  return (
    <div className="space-y-12">
      <section className="rounded-2xl border border-indigo-100 bg-white p-10 shadow-sm">
        <div className="max-w-3xl space-y-6">
          <p className="text-sm font-semibold uppercase tracking-wide text-indigo-500">
            Talent Setu Platform
          </p>
          <h1 className="text-3xl font-semibold text-zinc-900 sm:text-4xl">
            One workspace for learning, assessments, and recruitment proof.
          </h1>
          <p className="text-lg text-zinc-600">
            Build job-ready skills, challenge yourself with real-world
            scenarios, and showcase trusted results to recruiters—all backed by
            secure authentication and role-based access.
          </p>
          <div className="flex flex-wrap gap-3">
            <Link
              href={session ? "/dashboard" : "/login"}
              className="inline-flex items-center justify-center rounded-md bg-indigo-600 px-5 py-2.5 text-sm font-semibold text-white transition hover:bg-indigo-500"
            >
              {session ? "Continue to dashboard" : "Sign in"}
            </Link>
            {!session ? (
              <Link
                href="/signup"
                className="inline-flex items-center justify-center rounded-md border border-indigo-200 px-5 py-2.5 text-sm font-semibold text-indigo-600 transition hover:bg-indigo-50"
              >
                Create free account
              </Link>
            ) : null}
          </div>
        </div>
      </section>

      <section className="grid gap-6 md:grid-cols-3">
        {features.map((feature) => (
          <div
            key={feature.title}
            className="rounded-xl border border-zinc-200 bg-white p-6 shadow-sm"
          >
            <h2 className="text-lg font-semibold text-zinc-900">
              {feature.title}
            </h2>
            <p className="mt-2 text-sm text-zinc-600">{feature.description}</p>
          </div>
        ))}
      </section>
    </div>
  );
}
