version: "3.9"

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

  api:
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ./backend/api/.env.docker
    depends_on:
      - mongo

  ai-service:
    build:
      context: ./backend/ai-service
      dockerfile: Dockerfile
    ports:
      - "4100:4100"
    env_file:
      - ./backend/ai-service/.env.docker

  judge-service:
    build:
      context: ./backend/judge-service
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    env_file:
      - ./backend/judge-service/.env.docker

volumes:
  mongo-data:
