name: Semantic Release (per-package)

on:
  push:
    branches:
      - main

jobs:
  release-ui-tokens:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build ui-tokens
        run: npm --workspace=@talent-setu/ui-tokens run build

      - name: Run semantic-release for ui-tokens
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npx semantic-release --extends ./packages/ui-tokens/.releaserc.json

  release-ui-components:
    runs-on: ubuntu-latest
    needs: release-ui-tokens
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build ui-components
        run: npm --workspace=@talent-setu/ui-components run build

      - name: Run semantic-release for ui-components
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npx semantic-release --extends ./packages/ui-components/.releaserc.json
